// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUuBJkwmGpMBbDQge6lCwXpMYLCebbSr4',
    appId: '1:1006380648198:web:ff7520ccde275204d30087',
    messagingSenderId: '1006380648198',
    projectId: 'servicing-as',
    authDomain: 'servicing-as.firebaseapp.com',
    storageBucket: 'servicing-as.firebasestorage.app',
    measurementId: 'G-BR9VPFYD8G',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUuBJkwmGpMBbDQge6lCwXpMYLCebbSr4',
    appId: '1:1006380648198:web:0ff868d0f384dde8d30087',
    messagingSenderId: '1006380648198',
    projectId: 'servicing-as',
    authDomain: 'servicing-as.firebaseapp.com',
    storageBucket: 'servicing-as.firebasestorage.app',
    measurementId: 'G-2CQ93WZQTW',
  );
}
