begin;

create table if not exists public.password_reset_otps (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  email text not null,
  otp_hash text not null,
  reset_token_hash text,
  attempts integer not null default 0,
  expires_at timestamptz not null,
  reset_token_expires_at timestamptz,
  verified_at timestamptz,
  consumed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_password_reset_otps_email
on public.password_reset_otps (email);

create index if not exists idx_password_reset_otps_user_id
on public.password_reset_otps (user_id);

create index if not exists idx_password_reset_otps_active
on public.password_reset_otps (email, consumed_at, expires_at desc);

alter table public.password_reset_otps enable row level security;

drop policy if exists password_reset_blocked on public.password_reset_otps;

create policy password_reset_blocked
on public.password_reset_otps
for all
to anon, authenticated
using (false)
with check (false);

revoke all on table public.password_reset_otps from anon, authenticated;

commit;
